/*------------------------------------------------------------------------------------
  版权说明：Copyright 2023 Robottime(Beijing) Technology Co., Ltd. All Rights Reserved.
           Distributed under MIT license.See file LICENSE for detail or copy at
           https://opensource.org/licenses/MIT
           by 机器谱 2023-02-10 https://www.robotway.com/                                     
------------------------------------------------------------------------------------*/
int _ABVAR_1_i = 0 ;
int ardublockUltrasonicSensorCodeAutoGeneratedReturnCM(int trigPin, int echoPin)
{
  long duration;
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(20);
  digitalWrite(trigPin, LOW);
  duration = pulseIn(echoPin, HIGH);
  duration = duration / 59;
  if ((duration < 2) || (duration > 300)) return false;
  return duration;
}


void turnLeft();
void forward();
void back();

void setup()
{
  pinMode( 10, OUTPUT);
  pinMode( 6, OUTPUT);
  pinMode( 5, OUTPUT);
  pinMode( 9, OUTPUT);
  digitalWrite( 19 , LOW );

}

void loop()
{
  _ABVAR_1_i = 	ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 19 , 18 ) ;
  if (( ( ( _ABVAR_1_i ) <= ( 5 ) ) && ( ( _ABVAR_1_i ) > ( 0 ) ) ))
  {
    back();
    delay( 1000 );
    turnLeft();
    delay( 1500 );
  }
  else
  {
    forward();
  }
}

void forward()
{
  analogWrite(5 , 0);
  analogWrite(6 , 165);
  analogWrite(9 , 0);
  analogWrite(10 , 165);
}

void back()
{
  analogWrite(5 , 165);
  analogWrite(6 , 0);
  analogWrite(9 , 165);
  analogWrite(10 , 0);
}

void turnLeft()
{
  analogWrite(5 , 165);
  analogWrite(6 , 0);
  analogWrite(9 , 0);
  analogWrite(10 , 165);
}
